# Test SSH Connection to VPS
# This workflow tests SSH authentication before full deployment

name: Test SSH Connection

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Verify SSH key format in secret
        run: |
          echo "====== SSH Key Format Check (Base64) ======"
          echo "Base64 length:"
          echo "${{ secrets.VPS_SSH_KEY }}" | wc -c
          echo ""
          echo "Decoded key validation:"
          echo -n "${{ secrets.VPS_SSH_KEY }}" | base64 -d > /tmp/validate_key
          chmod 600 /tmp/validate_key
          ssh-keygen -l -f /tmp/validate_key || echo "Key decode failed"
          rm /tmp/validate_key
          echo "====== End Check ======"

      - name: Test SSH connection
        run: |
          mkdir -p ~/.ssh
          echo -n "${{ secrets.VPS_SSH_KEY }}" | base64 -d > ~/.ssh/test_key
          chmod 600 ~/.ssh/test_key
          ssh-keyscan -H -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

          echo "Testing SSH connection..."
          ssh -i ~/.ssh/test_key -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "echo 'SSH connection successful!' && whoami && pwd"

          if [ $? -eq 0 ]; then
            echo "✅ SSH authentication successful!"
          else
            echo "❌ SSH authentication failed!"
            exit 1
          fi
